-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  address_type USER-DEFINED DEFAULT 'home'::address_type,
  street text NOT NULL,
  city text NOT NULL,
  comuna text NOT NULL,
  region text NOT NULL,
  postal_code text,
  coordinates jsonb,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address_label character varying,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.booking_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  updated_by uuid NOT NULL,
  previous_status USER-DEFINED,
  new_status USER-DEFINED NOT NULL,
  update_reason text,
  update_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_updates_pkey PRIMARY KEY (id),
  CONSTRAINT booking_updates_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_updates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  service_category text NOT NULL,
  service_description text NOT NULL,
  requested_date date,
  requested_time_start time without time zone,
  requested_time_end time without time zone,
  confirmed_date date,
  confirmed_time_start time without time zone,
  confirmed_time_end time without time zone,
  estimated_price_clp integer CHECK (estimated_price_clp IS NULL OR estimated_price_clp >= 0),
  final_price_clp integer CHECK (final_price_clp IS NULL OR final_price_clp >= 0),
  platform_fee_clp integer,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::booking_status,
  urgency USER-DEFINED NOT NULL DEFAULT 'normal'::urgency_level,
  service_address_id uuid,
  service_address_text text,
  customer_notes text,
  provider_notes text,
  internal_notes text,
  work_started_at timestamp with time zone,
  work_completed_at timestamp with time zone,
  customer_confirmed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  service_price_clp integer CHECK (service_price_clp IS NULL OR service_price_clp >= 0),
  completed_at timestamp with time zone,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  escrow_transaction_id text,
  provider_response_at timestamp with time zone,
  cancellation_reason text,
  cancelled_by uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_service_address_id_fkey FOREIGN KEY (service_address_id) REFERENCES public.addresses(id),
  CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.users(id)
);
CREATE TABLE public.chilean_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  bank_code text NOT NULL,
  bank_name text NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['checking'::text, 'savings'::text, 'cuenta_rut'::text, 'cuenta_vista'::text])),
  account_number text NOT NULL,
  account_holder_rut text NOT NULL,
  account_holder_name text NOT NULL,
  is_verified boolean DEFAULT false,
  verification_method text,
  verification_attempts integer DEFAULT 0,
  verified_at timestamp with time zone,
  account_status text DEFAULT 'active'::text CHECK (account_status = ANY (ARRAY['active'::text, 'inactive'::text, 'blocked'::text, 'closed'::text])),
  last_validation timestamp with time zone,
  validation_frequency_days integer DEFAULT 30,
  is_primary boolean DEFAULT false,
  last_used timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chilean_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chilean_bank_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chilean_compliance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  rut_verification_status USER-DEFINED DEFAULT 'document_upload'::verification_stage,
  rut_verified_at timestamp with time zone,
  rut_verification_source text,
  sii_status text,
  sii_last_check timestamp with time zone,
  sii_tax_regime text,
  background_check_status USER-DEFINED DEFAULT 'document_upload'::verification_stage,
  background_check_completed_at timestamp with time zone,
  background_check_score integer CHECK (background_check_score >= 0 AND background_check_score <= 100),
  background_check_details jsonb DEFAULT '{}'::jsonb,
  business_entity_type USER-DEFINED,
  commercial_registration_number text,
  commercial_registration_date date,
  patente_municipal text,
  identity_document_url text,
  commercial_registration_url text,
  tax_document_url text,
  insurance_document_url text,
  overall_compliance_score integer DEFAULT 0 CHECK (overall_compliance_score >= 0 AND overall_compliance_score <= 100),
  compliance_expiry_date date,
  last_compliance_check timestamp with time zone DEFAULT now(),
  terms_accepted_at timestamp with time zone,
  privacy_policy_accepted_at timestamp with time zone,
  chilean_law_compliance_accepted_at timestamp with time zone,
  risk_level text DEFAULT 'medium'::text CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  risk_factors jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workflow_stage text DEFAULT 'initial'::text CHECK (workflow_stage = ANY (ARRAY['initial'::text, 'documents_uploaded'::text, 'rut_verified'::text, 'background_check'::text, 'tax_validated'::text, 'approved'::text, 'rejected'::text])),
  workflow_started_at timestamp with time zone DEFAULT now(),
  current_step_started_at timestamp with time zone DEFAULT now(),
  assigned_reviewer_id uuid,
  CONSTRAINT chilean_compliance_pkey PRIMARY KEY (id),
  CONSTRAINT chilean_compliance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chilean_compliance_assigned_reviewer_id_fkey FOREIGN KEY (assigned_reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.chilean_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  holiday_date date NOT NULL UNIQUE,
  holiday_name text NOT NULL,
  holiday_type text NOT NULL CHECK (holiday_type = ANY (ARRAY['national'::text, 'regional'::text, 'religious'::text, 'civic'::text])),
  is_business_day boolean DEFAULT false,
  applicable_regions ARRAY DEFAULT '{}'::text[],
  affects_service_delivery boolean DEFAULT true,
  premium_rate_multiplier numeric DEFAULT 1.5,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chilean_holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chilean_tax_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  booking_id uuid,
  document_type USER-DEFINED NOT NULL,
  document_number text NOT NULL,
  folio_number text,
  net_amount_clp integer NOT NULL,
  tax_amount_clp integer DEFAULT 0,
  total_amount_clp integer NOT NULL,
  retention_percentage numeric DEFAULT 0,
  retention_amount_clp integer DEFAULT 0,
  sii_document_id text,
  sii_status text DEFAULT 'pending'::text,
  sii_submitted_at timestamp with time zone,
  document_pdf_url text,
  document_xml_url text,
  issued_at timestamp with time zone DEFAULT now(),
  due_date date,
  paid_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chilean_tax_documents_pkey PRIMARY KEY (id),
  CONSTRAINT chilean_tax_documents_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id),
  CONSTRAINT chilean_tax_documents_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.compliance_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  changed_field text NOT NULL,
  old_value text,
  new_value text,
  changed_by uuid NOT NULL,
  change_reason text,
  workflow_stage text,
  verification_method text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT compliance_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT compliance_audit_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.customer_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  payment_type USER-DEFINED NOT NULL,
  provider_name character varying,
  masked_number character varying,
  cardholder_name character varying,
  expiry_month integer CHECK (expiry_month >= 1 AND expiry_month <= 12),
  expiry_year integer CHECK (expiry_year::numeric >= EXTRACT(year FROM now())),
  bank_name character varying,
  account_type character varying,
  rut_account_holder character varying,
  payment_token character varying,
  provider_customer_id character varying,
  is_default boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  last_used_at timestamp with time zone,
  verification_date timestamp with time zone,
  failed_attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT customer_payment_methods_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id)
);
CREATE TABLE public.data_protection_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  allow_profile_discovery boolean DEFAULT true,
  allow_review_display boolean DEFAULT true,
  allow_portfolio_public boolean DEFAULT true,
  allow_performance_stats boolean DEFAULT false,
  marketing_emails boolean DEFAULT false,
  service_notifications boolean DEFAULT true,
  review_reminders boolean DEFAULT true,
  newsletter_subscription boolean DEFAULT false,
  auto_delete_old_data boolean DEFAULT false,
  data_retention_years integer DEFAULT 7,
  ley_19628_consent boolean DEFAULT false,
  ley_19628_consent_date timestamp with time zone,
  gdpr_equivalent_consent boolean DEFAULT false,
  last_data_export_request timestamp with time zone,
  data_deletion_requested boolean DEFAULT false,
  data_deletion_scheduled timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_protection_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT data_protection_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_fraud_detection (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  document_type text NOT NULL,
  document_url text NOT NULL,
  fraud_risk_score integer DEFAULT 0 CHECK (fraud_risk_score >= 0 AND fraud_risk_score <= 100),
  fraud_indicators jsonb DEFAULT '[]'::jsonb,
  ai_confidence_score numeric DEFAULT 0,
  ai_model_version text,
  ai_analysis_timestamp timestamp with time zone,
  manual_review_required boolean DEFAULT false,
  manual_review_status text DEFAULT 'pending'::text CHECK (manual_review_status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_fraud_detection_pkey PRIMARY KEY (id),
  CONSTRAINT document_fraud_detection_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT document_fraud_detection_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.enhanced_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  reviewer_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  work_quality_rating integer CHECK (work_quality_rating >= 1 AND work_quality_rating <= 5),
  punctuality_rating integer CHECK (punctuality_rating >= 1 AND punctuality_rating <= 5),
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  cleanliness_rating integer CHECK (cleanliness_rating >= 1 AND cleanliness_rating <= 5),
  value_rating integer CHECK (value_rating >= 1 AND value_rating <= 5),
  review_text text,
  review_photos ARRAY DEFAULT '{}'::text[],
  authenticity_status USER-DEFINED DEFAULT 'pending'::review_authenticity,
  authenticity_score integer DEFAULT 50 CHECK (authenticity_score >= 0 AND authenticity_score <= 100),
  authenticity_flags jsonb DEFAULT '[]'::jsonb,
  helpfulness_score integer DEFAULT 0,
  helpful_votes integer DEFAULT 0,
  unhelpful_votes integer DEFAULT 0,
  provider_response text,
  provider_responded_at timestamp with time zone,
  is_featured boolean DEFAULT false,
  is_public boolean DEFAULT true,
  moderation_notes text,
  moderated_by uuid,
  moderated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT enhanced_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT enhanced_reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT enhanced_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT enhanced_reviews_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id),
  CONSTRAINT enhanced_reviews_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.users(id)
);
CREATE TABLE public.identity_verification_workflow (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  current_stage USER-DEFINED DEFAULT 'document_upload'::verification_stage,
  workflow_status text DEFAULT 'in_progress'::text CHECK (workflow_status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'failed'::text, 'on_hold'::text])),
  stages_completed jsonb DEFAULT '[]'::jsonb,
  stage_details jsonb DEFAULT '{}'::jsonb,
  requires_manual_approval boolean DEFAULT false,
  approval_reason text,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  rejection_details jsonb DEFAULT '{}'::jsonb,
  can_retry boolean DEFAULT true,
  retry_count integer DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  estimated_completion timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  epic_context text,
  automatic_checks_completed jsonb DEFAULT '[]'::jsonb,
  manual_review_notes text,
  CONSTRAINT identity_verification_workflow_pkey PRIMARY KEY (id),
  CONSTRAINT identity_verification_workflow_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT identity_verification_workflow_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.portfolio_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  service_category text NOT NULL,
  project_date date,
  project_location text,
  comuna character varying,
  before_photos ARRAY DEFAULT ARRAY[]::text[] CHECK (array_length(before_photos, 1) IS NULL OR array_length(before_photos, 1) <= 10),
  after_photos ARRAY DEFAULT ARRAY[]::text[] CHECK (array_length(after_photos, 1) IS NULL OR array_length(after_photos, 1) <= 10),
  video_urls ARRAY DEFAULT ARRAY[]::text[],
  project_duration_hours numeric,
  materials_used ARRAY,
  techniques_used ARRAY,
  challenges_overcome text,
  project_value_clp integer CHECK (project_value_clp IS NULL OR project_value_clp > 0),
  client_satisfaction_rating integer CHECK (client_satisfaction_rating >= 1 AND client_satisfaction_rating <= 5),
  is_featured boolean DEFAULT false,
  is_public boolean DEFAULT true,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])),
  verified_at timestamp with time zone,
  verified_by uuid,
  tags ARRAY DEFAULT ARRAY[]::text[],
  keywords ARRAY DEFAULT ARRAY[]::text[],
  view_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  share_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT portfolio_items_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_items_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id),
  CONSTRAINT portfolio_items_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_services (
  project_id text NOT NULL,
  service_id text NOT NULL,
  is_required boolean DEFAULT true,
  CONSTRAINT project_services_pkey PRIMARY KEY (service_id, project_id),
  CONSTRAINT project_services_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_types(id),
  CONSTRAINT project_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.project_types (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  estimated_duration text,
  avg_price_min integer,
  avg_price_max integer,
  complexity USER-DEFINED DEFAULT 'medium'::complexity_level,
  icon text,
  category USER-DEFINED NOT NULL,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.provider_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  week_start_date date NOT NULL,
  bookings_received integer DEFAULT 0,
  bookings_accepted integer DEFAULT 0,
  bookings_completed integer DEFAULT 0,
  bookings_cancelled integer DEFAULT 0,
  total_earnings_clp integer DEFAULT 0,
  average_job_value_clp integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  total_reviews integer DEFAULT 0,
  response_time_hours numeric DEFAULT 0,
  completion_rate_percentage numeric DEFAULT 0,
  on_time_rate_percentage numeric DEFAULT 0,
  customer_retention_rate numeric DEFAULT 0,
  market_rank integer,
  category_rank integer,
  area_rank integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT provider_analytics_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id)
);
CREATE TABLE public.provider_certifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  certification_name text NOT NULL,
  issuing_organization text NOT NULL,
  certification_number text,
  issued_date date NOT NULL,
  expiry_date date,
  verified_date timestamp with time zone,
  is_verified boolean DEFAULT false,
  verification_method text,
  verification_document_url text,
  chilean_certification_type text,
  government_registry_number text,
  skill_areas ARRAY DEFAULT '{}'::text[],
  certification_level text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_certifications_pkey PRIMARY KEY (id),
  CONSTRAINT provider_certifications_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id)
);
CREATE TABLE public.provider_profiles (
  user_id uuid NOT NULL,
  business_name text,
  description text,
  services ARRAY DEFAULT '{}'::text[],
  service_areas ARRAY DEFAULT '{}'::text[],
  hourly_rate_clp integer CHECK (hourly_rate_clp IS NULL OR hourly_rate_clp > 0),
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb DEFAULT '{}'::jsonb,
  background_check_status USER-DEFINED DEFAULT 'pending'::verification_status,
  is_available boolean DEFAULT true,
  rating numeric DEFAULT 0.00 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  total_jobs_completed integer DEFAULT 0,
  bank_account_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_name_search text,
  description_search text,
  specialties ARRAY DEFAULT '{}'::text[],
  response_time_hours integer DEFAULT 24,
  has_callout_fee boolean DEFAULT false,
  callout_fee_clp integer,
  min_job_value_clp integer,
  max_travel_distance_km integer DEFAULT 20,
  languages ARRAY DEFAULT '{Español}'::text[],
  certifications ARRAY DEFAULT '{}'::text[],
  is_available_today boolean DEFAULT true,
  working_hours jsonb DEFAULT '{"end": "18:00", "start": "08:00"}'::jsonb,
  coordinates point,
  search_vector tsvector,
  comuna text,
  verification_score integer DEFAULT 0,
  is_identity_verified boolean DEFAULT false,
  is_background_checked boolean DEFAULT false,
  professional_title character varying,
  years_of_experience integer CHECK (years_of_experience >= 0),
  education_background text,
  business_registration_number character varying,
  tax_id character varying,
  insurance_coverage jsonb DEFAULT '{}'::jsonb,
  travel_radius_km integer DEFAULT 10 CHECK (travel_radius_km > 0),
  minimum_job_value_clp integer DEFAULT 15000 CHECK (minimum_job_value_clp > 0),
  preferred_job_types ARRAY DEFAULT ARRAY[]::text[],
  average_rating numeric DEFAULT 0.00 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  success_rate_percentage numeric DEFAULT 0.00 CHECK (success_rate_percentage >= 0::numeric AND success_rate_percentage <= 100::numeric),
  preferred_payment_methods ARRAY DEFAULT ARRAY['bank_transfer'::text],
  holiday_availability jsonb DEFAULT '{"custom_dates": [], "chilean_holidays": false}'::jsonb,
  profile_completion_percentage integer DEFAULT 0 CHECK (profile_completion_percentage >= 0 AND profile_completion_percentage <= 100),
  business_entity_type text CHECK (business_entity_type = ANY (ARRAY['persona_natural'::text, 'empresa_individual'::text, 'sociedad_limitada'::text, 'sociedad_anonima'::text, 'microempresa'::text])),
  CONSTRAINT provider_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT provider_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.provider_projects (
  provider_id uuid NOT NULL,
  project_id text NOT NULL,
  base_price_clp integer,
  can_provide_estimate boolean DEFAULT true,
  portfolio_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_projects_pkey PRIMARY KEY (provider_id, project_id),
  CONSTRAINT provider_projects_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project_types(id),
  CONSTRAINT provider_projects_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id)
);
CREATE TABLE public.provider_services (
  provider_id uuid NOT NULL,
  service_id text NOT NULL,
  hourly_rate_clp integer,
  fixed_rate_clp integer,
  experience_years integer DEFAULT 0,
  is_primary_service boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_services_pkey PRIMARY KEY (service_id, provider_id),
  CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id),
  CONSTRAINT provider_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.review_fraud_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pattern_name text NOT NULL UNIQUE,
  pattern_description text,
  detection_rules jsonb NOT NULL,
  severity_level integer DEFAULT 5 CHECK (severity_level >= 1 AND severity_level <= 10),
  total_detections integer DEFAULT 0,
  false_positive_rate numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT review_fraud_patterns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewee_id uuid NOT NULL,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  work_quality_rating integer CHECK (work_quality_rating >= 1 AND work_quality_rating <= 5),
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  punctuality_rating integer CHECK (punctuality_rating >= 1 AND punctuality_rating <= 5),
  review_text text,
  review_title text,
  is_public boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES public.users(id)
);
CREATE TABLE public.search_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  search_type text NOT NULL,
  search_key text NOT NULL,
  location_key text,
  filters_hash text,
  provider_ids ARRAY,
  result_count integer,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  CONSTRAINT search_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_categories (
  id text NOT NULL,
  name text NOT NULL,
  icon text,
  description text,
  avg_price_min integer,
  avg_price_max integer,
  urgency_levels ARRAY DEFAULT '{}'::urgency_level[],
  color text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL,
  description text,
  icon_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trust_score_factors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  rut_verified_score integer DEFAULT 0,
  background_check_score integer DEFAULT 0,
  document_verification_score integer DEFAULT 0,
  profile_completion_score integer DEFAULT 0,
  review_history_score integer DEFAULT 0,
  payment_history_score integer DEFAULT 0,
  customer_testimonial_score integer DEFAULT 0,
  peer_endorsement_score integer DEFAULT 0,
  professional_certification_score integer DEFAULT 0,
  dispute_history_penalty integer DEFAULT 0,
  cancellation_penalty integer DEFAULT 0,
  fraud_risk_penalty integer DEFAULT 0,
  overall_trust_score integer DEFAULT 0 CHECK (overall_trust_score >= 0 AND overall_trust_score <= 100),
  trust_level text DEFAULT 'unverified'::text CHECK (trust_level = ANY (ARRAY['unverified'::text, 'basic'::text, 'verified'::text, 'premium'::text, 'elite'::text])),
  last_calculated timestamp with time zone DEFAULT now(),
  calculation_version integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trust_score_factors_pkey PRIMARY KEY (id),
  CONSTRAINT trust_score_factors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  phone_number text UNIQUE CHECK (phone_number IS NULL OR phone_number ~* '^\+56[0-9]{8,9}$'::text),
  full_name text NOT NULL,
  user_type USER-DEFINED NOT NULL DEFAULT 'customer'::user_type,
  avatar_url text,
  is_verified boolean DEFAULT false,
  email_verified_at timestamp with time zone,
  phone_verified_at timestamp with time zone,
  rut_number text CHECK (rut_number IS NULL OR rut_number ~* '^[0-9]{7,8}-[0-9kK]{1}$'::text),
  rut_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone DEFAULT now(),
  display_name character varying,
  whatsapp_number character varying CHECK (whatsapp_number IS NULL OR whatsapp_number::text ~* '^\+56[0-9]{8,9}$'::text),
  is_suspended boolean DEFAULT false,
  suspension_reason text,
  notification_preferences jsonb DEFAULT '{"sms": false, "push": true, "email": true, "whatsapp": false}'::jsonb,
  privacy_settings jsonb DEFAULT '{"show_email": false, "show_phone": false, "show_last_seen": true}'::jsonb,
  registration_source character varying,
  referral_code character varying UNIQUE,
  referred_by_id uuid,
  preferred_language character varying DEFAULT 'es'::character varying,
  timezone character varying DEFAULT 'America/Santiago'::character varying,
  last_active_at timestamp with time zone DEFAULT now(),
  profile_completion_percentage integer DEFAULT 0 CHECK (profile_completion_percentage >= 0 AND profile_completion_percentage <= 100),
  profile_completed_at timestamp with time zone,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  rut_verified_at timestamp with time zone,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  communication_preferences jsonb DEFAULT '{"sms": false, "push": true, "email": true, "whatsapp": true}'::jsonb,
  marketing_preferences jsonb DEFAULT '{"newsletter": false, "promotions": true, "recommendations": true}'::jsonb,
  comuna character varying,
  address text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_referred_by_id_fkey FOREIGN KEY (referred_by_id) REFERENCES public.users(id)
);
CREATE TABLE public.verification_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['cedula_front'::text, 'cedula_back'::text, 'selfie'::text, 'certificate'::text])),
  file_path text NOT NULL,
  file_name text NOT NULL,
  file_size integer NOT NULL,
  upload_status text DEFAULT 'uploading'::text CHECK (upload_status = ANY (ARRAY['uploading'::text, 'uploaded'::text, 'processing'::text, 'verified'::text, 'rejected'::text])),
  verification_result jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT verification_documents_pkey PRIMARY KEY (id),
  CONSTRAINT verification_documents_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id)
);
CREATE TABLE public.verification_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  workflow_step text NOT NULL CHECK (workflow_step = ANY (ARRAY['documents'::text, 'identity'::text, 'background'::text, 'admin_review'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'failed'::text])),
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  error_message text,
  retry_count integer DEFAULT 0,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT verification_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT verification_workflows_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider_profiles(user_id)
);